version: 2
executorType: docker
containerInfo:
  - image: maven:3.3.9-jdk-8
stages:
  build:
    workDir: ~/redis-stomp-relay
    steps:
      - type: checkout
      - type: shell
        command: strace mvn package
