spring:
  redis:
    host: your-hostname
    password: "your-password"
    port: 0000

stomp-redis-relay:
  channel-prefix: "/channel-prefix-used-by-the-client/"

logging.level.me.itzg.stomprelay: TRACE

